name: IssueChillAction
description: Sentiment analysis for issues
inputs:
  owner:
    description: repo owner
    required: true
  repo:
    description: repository name
    required: true
  issue:
    description: issue id
    required: true


runs:
  using: docker
  image: Dockerfile